// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fullfledgedparticipant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fullfledgedparticipant));
        
        string IMigrationMetadata.Id
        {
            get { return "201508060928120_full-fledged-participant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
