// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class office_sotfDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(office_sotfDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201504200822171_office_sotfDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
