// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rename_freelance_calendar_statuses_to_availability_statuses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_freelance_calendar_statuses_to_availability_statuses));
        
        string IMigrationMetadata.Id
        {
            get { return "201504291325240_rename_freelance_calendar_statuses_to_availability_statuses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
