// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class offices_and_office_types_and_legalEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(offices_and_office_types_and_legalEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "201504200816362_offices_and_office_types_and_legalEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
