// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_properties_to_order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_properties_to_order));
        
        string IMigrationMetadata.Id
        {
            get { return "201508041014109_add_properties_to_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
