// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_calendarPeriods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_calendarPeriods));
        
        string IMigrationMetadata.Id
        {
            get { return "201506081058385_update_calendarPeriods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
