// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_double_key_in_phone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_double_key_in_phone));
        
        string IMigrationMetadata.Id
        {
            get { return "201505270949199_fix_double_key_in_phone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
