// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_regions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_regions));
        
        string IMigrationMetadata.Id
        {
            get { return "201505060939542_added_regions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
