// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_soft_delete_to_freelance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_soft_delete_to_freelance));
        
        string IMigrationMetadata.Id
        {
            get { return "201505281749237_add_soft_delete_to_freelance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
