// <auto-generated />
namespace VTraktate.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_grade_extra_foreignKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_grade_extra_foreignKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201506251943419_fix_grade_extra_foreignKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
