//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTraktate.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public bool Preferred { get; set; }
        public string EmailAddress { get; set; }
        public string Description { get; set; }
        public int PersonID { get; set; }
    
        public virtual PersonalInfo Person { get; set; }
    }
}
