//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTraktate.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public Employment()
        {
            this.CalendarPeriods = new HashSet<CalendarPeriod>();
        }
    
        public int Id { get; set; }
        public int OfficeID { get; set; }
        public int TitleID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comment { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ProviderID { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual EmployeeTitle Title { get; set; }
        public virtual EmploymentStatus Status { get; set; }
        public virtual PersonalInfo CreatedBy { get; set; }
        public virtual PersonalInfo ModifiedBy { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<CalendarPeriod> CalendarPeriods { get; set; }
    }
}
