//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTraktate.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.ProviderAliases = new HashSet<Provider>();
            this.Employments = new HashSet<Employment>();
            this.CalendarPeriods = new HashSet<CalendarPeriod>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string OfficialName { get; set; }
        public string Code { get; set; }
        public Nullable<int> old_id { get; set; }
    
        public virtual ICollection<Provider> ProviderAliases { get; set; }
        public virtual ICollection<Employment> Employments { get; set; }
        public virtual ICollection<CalendarPeriod> CalendarPeriods { get; set; }
    }
}
