//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTraktate.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public PersonalInfo()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.ModifiedBy = new HashSet<PersonalInfo>();
            this.CreatedBy = new HashSet<PersonalInfo>();
            this.EmailAddresses = new HashSet<Email>();
            this.CreatedEmployments = new HashSet<Employment>();
            this.ModifiedEmployments = new HashSet<Employment>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string AlternateName { get; set; }
        public string AddressName { get; set; }
        public string Initials { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> old_id { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<PersonalInfo> ModifiedBy { get; set; }
        public virtual PersonalInfo Modifieds { get; set; }
        public virtual ICollection<PersonalInfo> CreatedBy { get; set; }
        public virtual PersonalInfo Creatures { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<Email> EmailAddresses { get; set; }
        public virtual ICollection<Employment> CreatedEmployments { get; set; }
        public virtual ICollection<Employment> ModifiedEmployments { get; set; }
    }
}
