//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTraktate.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Personalities = new HashSet<PersonalInfo>();
            this.Employments = new HashSet<Employment>();
            this.CalendarPeriods = new HashSet<CalendarPeriod>();
            this.Freelances = new HashSet<Freelance>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public ProviderTypes TypeID { get; set; }
        public Nullable<int> RepresentedOfficeID { get; set; }
        public Nullable<int> old_p_id { get; set; }
    
        public virtual Office RepresentedOffice { get; set; }
        public virtual ICollection<PersonalInfo> Personalities { get; set; }
        public virtual ProviderType ProviderType { get; set; }
        public virtual ICollection<Employment> Employments { get; set; }
        public virtual ICollection<CalendarPeriod> CalendarPeriods { get; set; }
        public virtual ICollection<Freelance> Freelances { get; set; }
    }
}
