//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTraktate.DAL
{
    using System;
    
    public enum ProviderTypes : int
    {
        Employee = 0,
        Freelancer = 1,
        Contractor = 2,
        Office = 3
    }
}
