//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTraktate.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TraktatData : DbContext
    {
        public TraktatData()
            : base("name=TraktatData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<PersonalInfo> PersonalInfos { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Provider> Providers1 { get; set; }
        public virtual DbSet<ProviderType> ProviderTypes { get; set; }
        public virtual DbSet<Email> Emails1 { get; set; }
        public virtual DbSet<EmployeeTitle> EmployeeTitles { get; set; }
        public virtual DbSet<EmploymentStatus> EmploymentStatuses { get; set; }
        public virtual DbSet<Employment> Employments1 { get; set; }
        public virtual DbSet<CalendarPeriod> CalendarPeriods { get; set; }
        public virtual DbSet<FreelanceStatus> FreelanceStatuses { get; set; }
        public virtual DbSet<Freelance> Freelances { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
    }
}
